[package]
name = "lmt-checker"
description = "Type checker and semantic analysis for LMT"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
categories.workspace = true
keywords.workspace = true
readme.workspace = true

[features]
default = ["cvc5"]
cvc5 = ["lmt-solver/cvc5"]

[dependencies]

lmt-diagnostics.workspace = true
lmt-index.workspace = true
lmt-solver.workspace = true
lmt-syntax.workspace = true

facet = { workspace = true }
facet-core = { workspace = true }
facet-error = { workspace = true }
facet-path = { workspace = true }
facet-reflect = { workspace = true }

parking_lot.workspace = true
picante.workspace = true
thiserror.workspace = true

[lints]
workspace = true
