[package]
name = "lmt-parser"

edition.workspace = true
version.workspace = true

[features]
default = ["color", "serde"]

color = ["lmt-report/color"]
serde = ["chumsky/serde", "dep:serde", "lmt-number/serde", "lmt-report/serde"]

[dependencies]
lmt-number = { path = "../../util/number", version = "0.1.0-alpha.0", public = true }
lmt-report = { path = "../../util/report", version = "0.1.0-alpha.0", public = true }

chumsky = { version = "0.12.0", features = [
  "extension",
  # "label",
  "lexical-numbers",
  "nightly",
  "pratt",
], public = true }
serde = { version = "1.0", features = [
  "derive",
], optional = true, public = true }
