[package]
name = "lmt-generator"

edition.workspace = true
version.workspace = true

[features]
default = []

[dependencies]
# lmt-compiler = { path = "../../core/compiler", version = "0.1.0-alpha.0", public = true }
lmt-number = { path = "../../util/number", version = "0.1.0-alpha.0", public = true }
lmt-parser = { path = "../../core/parser", version = "0.1.0-alpha.0", public = true }
lmt-report = { path = "../../util/report", version = "0.1.0-alpha.0", public = true }
lmt-synthesis = { path = "../../core/synthesis", version = "0.1.0-alpha.0", public = true }

cvc5-rs = { version = "0.3.2" }

[lints]
workspace = true
