[package]
edition.workspace = true
name = "lmt-number"
version.workspace = true

[lints]
workspace = true

[features]
default = []

serde = ["dep:bitcode", "fraction/with-serde-support"]

[dependencies]
# num-bigint = "0.4.4"
# num-integer = "0.1.46"
# num-rational = "0.4.1"
num-traits = { version = "0.2.18", public = true }

bitcode = { version = "0.6.0", features = [
  "serde",
], optional = true, public = true }
fraction = { version = "0.15.1", public = true }
