[package]
name = "lmt-diagnostics"
description = "Diagnostics and reporting utilities for LMT"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
categories.workspace = true
keywords.workspace = true
readme.workspace = true

[features]

default = ["fancy", "fs"]

fancy = ["dep:crossterm", "dep:line-col", "dep:rand"]
fs = []

[dependencies]

anyhow = { workspace = true }
picante = { workspace = true }
tacos = { workspace = true }

facet = { workspace = true }
facet-core = { workspace = true }
facet-error = { workspace = true }
facet-path = { workspace = true }
facet-reflect = { workspace = true }

crossterm = { workspace = true, optional = true }
line-col = { workspace = true, optional = true }
rand = { workspace = true, optional = true }

lmt-index = { path = "../index" }

[lints]
workspace = true
