[package]
name = "lmt-syntax"
description = "Parser and syntax utilities for LMT"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
categories.workspace = true
keywords.workspace = true
readme.workspace = true

[dependencies]

lmt-diagnostics.workspace = true

anyhow.workspace = true
ordered-float.workspace = true
picante.workspace = true
tacos.workspace = true

facet = { workspace = true }
facet-core = { workspace = true }
facet-error = { workspace = true }
facet-path = { workspace = true }
facet-reflect = { workspace = true }

[dev-dependencies]
insta.workspace = true
walkdir.workspace = true

[lints]
workspace = true
