[package]
name = "lmt-solver"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
categories.workspace = true
keywords.workspace = true
readme.workspace = true

[features]
default = ["cvc5"]
cvc5 = ["cvc5-rs"]

[dependencies]

lmt-diagnostics.workspace = true
lmt-index.workspace = true
lmt-syntax.workspace = true

facet = { version = "=0.44.1", features = ["ordered-float"] }
facet-core = { version = "=0.44.1" }
facet-dessert = { version = "=0.44.1" }
facet-error = { version = "=0.44.1" }
facet-path = { version = "=0.44.1" }
facet-postcard = { version = "=0.44.1" }
facet-reflect = { version = "=0.44.1" }
facet-value = { version = "=0.44.1" }

anyhow.workspace = true
cvc5-rs = { workspace = true, optional = true }
parking_lot.workspace = true
thiserror.workspace = true

[lints]
workspace = true
