[package]
name = "lmt-report"

edition.workspace = true
version.workspace = true

[lints]
workspace = true

[features]
default = ["color", "serde"]

color = ["miette/fancy", "miette/syntect-highlighter"]
serde = ["dep:serde", "miette/serde"]

[dependencies]
miette = "7.2.0"
thiserror = "1.0"

serde = { version = "1.0", features = [
  "derive",
], optional = true, public = true }
